### ISSUE TITLE
panic: interface conversion: interface {} is float64, not string

### ISSUE THREAD

**Issue by Pixinger** [mabunixda/wattpilot#24]
Hi, I'm running evcc on VirtualBox/Ubuntu test setup.

I have the nightly build installed:
> evcc/lunar,now 0.119.5+1694830319 amd64  [installiert]

Starting evcc with a connected (+RFID) car will no longer start. It reports the following output:

```
[main  ] INFO 2023/09/16 07:06:36 evcc 0.119.5 (3a5d2c42)
[main  ] INFO 2023/09/16 07:06:36 using config file: /etc/evcc.yaml
[main  ] INFO 2023/09/16 07:06:36 starting ui and api at :7070
[lp-1  ] WARN 2023/09/16 07:06:37 locking phase config to 1p for switchable charger
[site  ] INFO 2023/09/16 07:06:37 site config:
[site  ] INFO 2023/09/16 07:06:37   meters:      grid ✓ pv ✓ battery ✓
[site  ] INFO 2023/09/16 07:06:37     grid:      power ✓ energy ✗ currents ✗
[site  ] INFO 2023/09/16 07:06:37     pv 1:      power ✓ energy ✗ currents ✗
[site  ] INFO 2023/09/16 07:06:37     battery 1: power ✓ energy ✗ currents ✗ soc ✓ capacity ✗
[site  ] INFO 2023/09/16 07:06:37   vehicles:
[site  ] INFO 2023/09/16 07:06:37     vehicle 1: range ✗ finish ✗ status ✗ climate ✗ wakeup ✗
[lp-1  ] INFO 2023/09/16 07:06:37 loadpoint 1:
[lp-1  ] INFO 2023/09/16 07:06:37   mode:        pv
[lp-1  ] INFO 2023/09/16 07:06:37   charger:     power ✓ energy ✗ currents ✓ phases ✓ wakeup ✗
[lp-1  ] INFO 2023/09/16 07:06:37   meters:      charge ✓
[lp-1  ] INFO 2023/09/16 07:06:37     charge:    power ✓ energy ✗ currents ✓
[lp-1  ] INFO 2023/09/16 07:06:37 vehicle updated: unknown -> ##MyCar##
[lp-1  ] INFO 2023/09/16 07:06:38 car connected
panic: interface conversion: interface {} is float64, not string

goroutine 12 [running]:
github.com/mabunixda/wattpilot.(*Wattpilot).GetRFID(0xc001582040?)
	github.com/mabunixda/wattpilot@v1.6.2-0.20230908111052-8ceeab68807a/wattpilot.go:724 +0x70
github.com/evcc-io/evcc/charger.(*Wattpilot).Identify(0xc0013dff80?)
	github.com/evcc-io/evcc/charger/fronius-wattpilot.go:135 +0x16
github.com/evcc-io/evcc/core.(*Loadpoint).createSession(0xc000101800)
	github.com/evcc-io/evcc/core/loadpoint_session.go:40 +0xff
github.com/evcc-io/evcc/core.(*Loadpoint).evVehicleConnectHandler(0xc000101800)
	github.com/evcc-io/evcc/core/loadpoint.go:470 +0x265
reflect.Value.call({0x2225da0?, 0xc000646490?, 0x10?}, {0x275e63b, 0x4}, {0x4ebb240, 0x0, 0x7f8bdb02c108?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x2225da0?, 0xc000646490?, 0x0?}, {0x4ebb240?, 0x0?, 0xc000165490?})
	reflect/value.go:380 +0xb9
github.com/asaskevich/EventBus.(*EventBus).doPublish(0x2324d80?, 0xc000e3c240, {0x276ae3b?, 0xc0006464b0?}, {0x0?, 0xc000165480?, 0x10?})
	github.com/asaskevich/EventBus@v0.0.0-20200907212545-49d423059eef/event_bus.go:160 +0x4d
github.com/asaskevich/EventBus.(*EventBus).Publish(0xc0013df2a0, {0x276ae3b, 0x7}, {0x0, 0x0, 0x0})
	github.com/asaskevich/EventBus@v0.0.0-20200907212545-49d423059eef/event_bus.go:144 +0x5bf
github.com/evcc-io/evcc/core.(*Loadpoint).updateChargerStatus(0xc000101800)
	github.com/evcc-io/evcc/core/loadpoint.go:890 +0x46b
github.com/evcc-io/evcc/core.(*Loadpoint).Update(0xc000101800, 0x3ff0000000000000?, 0x0, 0x0?, 0x0?, 0x3ff0000000000000, 0xc0009819c8, 0x0)
	github.com/evcc-io/evcc/core/loadpoint.go:1505 +0x212
github.com/evcc-io/evcc/core.(*Site).update(0xc0007cf600, {0x31a5e98?, 0xc000101800})
	github.com/evcc-io/evcc/core/site.go:772 +0x5da
github.com/evcc-io/evcc/core.(*Site).Run(0xc0007cf600, 0xc001472d80, 0x6fc23ac00)
	github.com/evcc-io/evcc/core/site.go:861 +0x206
github.com/evcc-io/evcc/cmd.runRoot.func4()
	github.com/evcc-io/evcc/cmd/root.go:282 +0x25
created by github.com/evcc-io/evcc/cmd.runRoot in goroutine 1
	github.com/evcc-io/evcc/cmd/root.go:281 +0x1a13
```

The last working version seems to be "0.119.4+1693793528" (although I did not test all nightly steps).

This is the most relevant part of the evcc.yaml. If you need more information, let me know:
```
chargers:
  - type: template
    template: fronius-wattpilot
    host: 192.168.X.X
    password: ###
    name: wallbox3

loadpoints:
  - title: Garage
    charger: wallbox3
    mode: pv
    phases: 1
    mincurrent: 6
    maxcurrent: 16
    resetOnDisconnect: true
    vehicle: ##MyCar##
    enable:
      threshold: 0
      delay: 3m
    disable:
      threshold: 0
      delay: 2m
    guardduration: 10m

vehicles:
  - name:  ##MyCar##
    type: template
    template: offline
    title: 'some title'
    capacity: 50 
#    identifiers:
#      - 0 # RFID token ID
#      - 1 # RFID token ID
#      - 2 # RFID token ID
#      - 3 # RFID token ID
```

Thanks for your work on the integration. 

Kind regards
Pix
